#!/bin/bash

FOLDERS=(
  ~/.config/tmux/
  ~/.config/ghostty/
  ~/.config/ghostty/themes
  ~/.config/aerospace/
	~/.config/nvim/lua/configs/
	~/.config/nvim/lua/plugins/
	~/.local/share/nvim/lazy/alpha-nvim/lua/alpha/themes/
	)

install_dots() {
  echo "========= linking zshrc ========="
  ln -Ffv ./.zshrc ~/.zshrc && printf "\n"

  echo "========= linking zshrc ========="
  ln -Ffv ./.config/prompt.zsh ~/.config/ && printf "\n"

  echo "========= linking tmux.conf and theme ========="
  ln -Ffv ./.config/tmux/tmux.conf ~/.config/tmux/tmux.conf && printf "\n"
  ln -Ffv ./.config/tmux/nova.tmux ~/.config/tmux/nova.tmux && printf "\n"

  echo "========= linking ghostty config ========="
  ln -Ffv ./.config/ghostty/config ~/.config/ghostty/config && printf "\n"
  ln -Ffv ./.config/ghostty/config/themes ~/.config/ghostty/config/themes && printf "\n"

  echo "========= linking ghostty config ========="
  ln -Ffv ./.config/aerospace/aerospace.toml ~/.config/aerospace/aerospace.toml && printf "\n"

  echo "========= linking init.lua  ========="
  ln -Ffv .config/nvim/init.lua ~/.config/nvim/init.lua && printf "\n"

  echo "========= linking nvim lua configs ========="
  ln -Ffv .config/nvim/lua/configs/* ~/.config/nvim/lua/configs/ && printf "\n"

  echo "========= linking nvim lazy config ========="
  ln -Ffv .config/nvim/lua/* ~/.config/nvim/lua/ && printf "\n"

  echo "========= linking nvim lua plugins ========="
  ln -Ffv .config/nvim/lua/plugins/* ~/.config/nvim/lua/plugins/ && printf "\n"

  echo "========= linking startup.nvim dashboard ========="
  ln -Ffv .local/share/nvim/lazy/alpha-nvim/lua/alpha/themes/dashboard.lua \
    ~/.local/share/nvim/lazy/alpha-nvim/lua/alpha/themes/dashboard.lua \
    && printf "\n"
}

printf "Your installed dotfiles will be overwritten. \n\nAre you sure you want to continue? y/n\n"

read -r install
if [ "$install" != "${install#[Yy]}" ] ;then 
  for folder in ${FOLDERS[@]}; do
	  if [[ ! -d $folder ]]; then
	    mkdir -p ${folder}
	  fi
  done

  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  git clone https://github.com/jeffreytse/zsh-vi-mode ~/git/zsh-vi-mode
  git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/git/zsh-syntax-highlighting
  install_dots
else
  exit
fi

