#!/bin/bash

install_dots() {
  echo "========= linking init.lua  ========="
  ln -Fiv .config/nvim/init.lua ~/.config/nvim/init.lua && printf "\n"

  # echo "========= linking zshrc ========="
  # ln -Fiv ./.zshrc ~/.zshrc && printf "\n"
  
  echo "========= linking nvim lua configs ========="
  ln -Fiv .config/nvim/lua/* ~/.config/nvim/lua/ && printf "\n"

  echo "========= linking startup.nvim dashboard ========="
  ln -Fiv ./.local/share/nvim/site/pack/packer/start/startup.nvim/lua/startup/themes/dashboard.lua \
    ~/.local/share/nvim/site/pack/packer/start/startup.nvim/lua/startup/themes/dashboard.lua \
    && printf "\n"
}

printf "Your installed dotfiles will be overwritten. \n\nAre you sure you want to continue? y/n\n"
read -r install
if [ "$install" != "${install#[Yy]}" ] ;then 
  install_dots
else
  exit
fi

